### ISSUE TITLE
Why use php instead of go?

### ISSUE THREAD

**Issue by QiaoHao9** [goacs/goacs#6]
I saw earlier that you were using Go to write the ACS server, why did you switch to PHP? What were some of the difficulties that led you to switch languages?

**Comment by pingwiniasty** [comment]
Hi, main difficulties was not good knowledge of Go and libraries. The code was bad designed, I not used any ORM to manage database, only raw SQL with sqlx + custom sql builder. Handle non standard variable types with sqlx makes me crazy... Always need to write additional code. I also have problems with API and Request validation. The last thought is deadline - now we are start testing on production enviorment.

Current version runs on PHP8 and swoole. It's realy fast too, inform request spends ~40ms (due database writes)
